import SwiftUI
import SwiftData

struct BudgetHomeView: View {
    @Query private var budgets: [Budget]; @Query private var transactions: [FinanceTransaction]
    @State private var period = BudgetPeriod.month; @State private var date = Date.now; @State private var adding = false
    private var visible: [Budget] { budgets.filter { $0.period == period } }
    private var totalBudget: Decimal { visible.filter { $0.category == nil }.reduce(0) { $0 + $1.amount } }
    private var used: Decimal { FinanceCalculator.total(FinanceCalculator.transactions(transactions, in: date, period: period), type: .expense) }
    var body: some View { NavigationStack { List { Section { Picker("预算周期", selection: $period) { ForEach(BudgetPeriod.allCases) { Text($0.title).tag($0) } }.pickerStyle(.segmented); MonthSelector(date: $date) }; Section { BudgetSummaryCard(budget: totalBudget, used: used).listRowInsets(.init()).listRowBackground(Color.clear) }; if visible.isEmpty { ContentUnavailableView("还没有设置预算", systemImage: "wallet.bifold", description: Text("预算使用金额会根据真实交易自动计算")); Button("设置预算") { adding = true }.frame(maxWidth: .infinity) } else { Section("分类预算") { ForEach(visible.filter { $0.category != nil }) { budget in NavigationLink { BudgetDetailView(budget: budget, transactions: transactions, date: date) } label: { BudgetRow(budget: budget, used: FinanceCalculator.used(budget, transactions: transactions, viewedDate: date)) } } } } }.navigationTitle("预算").toolbar { Button("新增预算", systemImage: "plus") { adding = true } }.sheet(isPresented: $adding) { BudgetEditorView(defaultPeriod: period) } } }
}

struct BudgetSummaryCard: View { let budget: Decimal; let used: Decimal; private var progress: Double { budget > 0 ? used.doubleValue / budget.doubleValue : 0 }; var body: some View { VStack(alignment: .leading, spacing: 14) { Text("总预算").font(.subheadline).foregroundStyle(.secondary); AmountText(amount: budget, font: .title.bold()); HStack { Text("已使用 " + CurrencyFormatter.string(used)); Spacer(); Text(used > budget && budget > 0 ? "超支 " + CurrencyFormatter.string(used - budget) : "剩余 " + CurrencyFormatter.string(max(0, budget - used))) }.font(.subheadline); ProgressView(value: min(progress, 1)).tint(progress >= 1 ? .red : progress >= 0.8 ? .orange : .accentColor); Text(progress.formatted(.percent.precision(.fractionLength(1)))).font(.caption).foregroundStyle(progress >= 1 ? .red : .secondary) }.padding(20).background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 20)) } }
struct BudgetRow: View { let budget: Budget; let used: Decimal; private var progress: Double { budget.amount > 0 ? used.doubleValue / budget.amount.doubleValue : 0 }; var body: some View { VStack(alignment: .leading, spacing: 9) { HStack { CategoryIcon(category: budget.category, size: 36); Text(budget.category?.name ?? "总预算").font(.headline); Spacer(); Text(progress.formatted(.percent.precision(.fractionLength(0)))).foregroundStyle(progress > 1 ? .red : .secondary) }; ProgressView(value: min(progress, 1)).tint(progress > 1 ? .red : .accentColor); Text(used > budget.amount ? "超支 " + CurrencyFormatter.string(used - budget.amount) : "剩余 " + CurrencyFormatter.string(budget.amount - used)).font(.caption).foregroundStyle(used > budget.amount ? .red : .secondary) } } }

struct BudgetDetailView: View { @Environment(\.modelContext) private var context; @Environment(\.dismiss) private var dismiss; let budget: Budget; let transactions: [FinanceTransaction]; let date: Date; @State private var editing = false; @State private var deleting = false; var body: some View { List { Section { BudgetSummaryCard(budget: budget.amount, used: FinanceCalculator.used(budget, transactions: transactions, viewedDate: date)).listRowInsets(.init()).listRowBackground(Color.clear) }; Section("设置") { LabeledContent("分类", value: budget.category?.name ?? "全部分类"); LabeledContent("周期", value: budget.period.title); LabeledContent("开始日期", value: budget.startDate.formatted(DateFormats.shortDay)); LabeledContent("超预算提醒", value: budget.isNotificationEnabled ? "开启" : "关闭") }; Section { Button("删除预算", systemImage: "trash", role: .destructive) { deleting = true }.frame(maxWidth: .infinity) } }.navigationTitle(budget.category?.name ?? "总预算").toolbar { Button("编辑") { editing = true } }.sheet(isPresented: $editing) { BudgetEditorView(budget: budget) }.confirmationDialog("删除预算？", isPresented: $deleting) { Button("删除", role: .destructive) { context.delete(budget); try? context.save(); dismiss() } } } }

struct BudgetEditorView: View { @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context; @Query private var ledgers: [Ledger]; @Query(sort: \FinanceCategory.sortOrder) private var categories: [FinanceCategory]; var budget: Budget?; @State private var amount: String; @State private var period: BudgetPeriod; @State private var date: Date; @State private var ledger: Ledger?; @State private var category: FinanceCategory?; @State private var notification: Bool; @State private var errorMessage: String?; init(budget: Budget? = nil, defaultPeriod: BudgetPeriod = .month) { self.budget = budget; _amount = State(initialValue: budget.map { "\($0.amount)" } ?? ""); _period = State(initialValue: budget?.period ?? defaultPeriod); _date = State(initialValue: budget?.startDate ?? .now); _ledger = State(initialValue: budget?.ledger); _category = State(initialValue: budget?.category); _notification = State(initialValue: budget?.isNotificationEnabled ?? false) }; var body: some View { NavigationStack { Form { TextField("预算金额", text: $amount).keyboardType(.decimalPad); Picker("周期", selection: $period) { ForEach(BudgetPeriod.allCases) { Text($0.title).tag($0) } }; Picker("账本", selection: $ledger) { Text("全部账本").tag(nil as Ledger?); ForEach(ledgers) { Text($0.name).tag(Optional($0)) } }; Picker("分类", selection: $category) { Text("全部分类（总预算）").tag(nil as FinanceCategory?); ForEach(categories.filter { $0.type == .expense && $0.isEnabled }) { Text($0.name).tag(Optional($0)) } }; DatePicker("开始日期", selection: $date, displayedComponents: .date); Toggle("超预算提醒", isOn: $notification) }.navigationTitle(budget == nil ? "新增预算" : "编辑预算").toolbar { ToolbarItem(placement: .cancellationAction) { Button("取消") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("保存") { save() } } }.alert("无法保存", isPresented: .constant(errorMessage != nil)) { Button("好") { errorMessage = nil } } message: { Text(errorMessage ?? "") } } }; private func save() { guard let value = Decimal(string: amount), value > 0 else { errorMessage = "预算金额必须大于 0"; return }; let model = budget ?? Budget(amount: value); model.amount = value; model.periodRaw = period.rawValue; model.startDate = date; model.ledger = ledger; model.category = category; model.isNotificationEnabled = notification; if budget == nil { context.insert(model) }; do { try context.save(); dismiss() } catch { errorMessage = error.localizedDescription } } }
