import SwiftUI
import SwiftData
import Charts

struct StatisticsHomeView: View {
    @Query private var transactions: [FinanceTransaction]
    @State private var period = BudgetPeriod.month; @State private var date = Date.now; @State private var chartType = TransactionType.expense
    private var current: [FinanceTransaction] { FinanceCalculator.transactions(transactions, in: date, period: period) }
    private var expense: Decimal { FinanceCalculator.total(current, type: .expense) }; private var income: Decimal { FinanceCalculator.total(current, type: .income) }
    private var categoryTotals: [CategoryTotal] { Dictionary(grouping: current.filter { $0.type == chartType && $0.category != nil }, by: { $0.category?.id }).compactMap { key, values in guard key != nil, let category = values.first?.category else { return nil }; return CategoryTotal(id: category.id, category: category, amount: values.reduce(0) { $0 + $1.amount }) }.sorted { $0.amount > $1.amount } }
    var body: some View { NavigationStack { ScrollView { VStack(spacing: 20) { Picker("时间范围", selection: $period) { Text("月").tag(BudgetPeriod.month); Text("年").tag(BudgetPeriod.year) }.pickerStyle(.segmented); MonthSelector(date: $date); SummaryCard(expense: expense, income: income); Picker("统计类型", selection: $chartType) { Text("支出").tag(TransactionType.expense); Text("收入").tag(TransactionType.income) }.pickerStyle(.segmented); if categoryTotals.isEmpty { ContentUnavailableView("暂无统计数据", systemImage: "chart.pie", description: Text("记录交易后会自动生成图表")) } else { donutChart; VStack(spacing: 0) { ForEach(categoryTotals) { item in NavigationLink { CategoryStatisticsDetailView(item: item, transactions: current.filter { $0.category?.id == item.id }) } label: { HStack { CategoryIcon(category: item.category); Text(item.category.name).foregroundStyle(.primary); Spacer(); VStack(alignment: .trailing) { AmountText(amount: item.amount); Text(percent(item.amount)).font(.caption).foregroundStyle(.secondary) } }.padding(.vertical, 10) }; Divider() } }.padding(.horizontal).background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 18)) } }.padding() }.navigationTitle("统计") } }
    private var donutChart: some View { ZStack { Chart(categoryTotals) { item in SectorMark(angle: .value("金额", item.amount.doubleValue), innerRadius: .ratio(0.62), angularInset: 2).foregroundStyle(by: .value("分类", item.category.name)).cornerRadius(3) }.chartLegend(.hidden).frame(height: 260).accessibilityLabel("\(chartType.title)分类图"); VStack { Text(chartType.title).font(.caption).foregroundStyle(.secondary); AmountText(amount: categoryTotals.reduce(0) { $0 + $1.amount }, font: .title2.bold()) } } }
    private func percent(_ value: Decimal) -> String { let total = categoryTotals.reduce(0) { $0 + $1.amount }; return (total > 0 ? value.doubleValue / total.doubleValue : 0).formatted(.percent.precision(.fractionLength(1))) }
}

struct CategoryStatisticsDetailView: View { let item: CategoryTotal; let transactions: [FinanceTransaction]; var body: some View { List { Section { VStack(spacing: 12) { CategoryIcon(category: item.category, size: 60); AmountText(amount: item.amount, font: .largeTitle.bold()); Text("本期总金额").foregroundStyle(.secondary) }.frame(maxWidth: .infinity).padding() }; Section("交易列表") { ForEach(transactions) { transaction in NavigationLink { TransactionDetailView(transaction: transaction) } label: { TransactionRow(transaction: transaction) } } } }.navigationTitle(item.category.name) } }
