import SwiftUI
import SwiftData

struct AccountsHomeView: View {
    @Query(sort: \Account.createdAt) private var accounts: [Account]
    @AppStorage("hideAmounts") private var hideAmounts = false
    @State private var editing: Account?
    @State private var adding = false
    var body: some View { NavigationStack { List { Section { netWorthCard.listRowInsets(.init()).listRowBackground(Color.clear) }; if accounts.isEmpty { ContentUnavailableView("还没有账户", systemImage: "square.stack.3d.up", description: Text("添加账户后，交易会自动更新余额")) } else { accountSection("资金账户", accounts.filter { !$0.type.isLiability && ![.investment, .fund, .stock].contains($0.type) }); accountSection("信用与负债", accounts.filter { $0.type.isLiability }); accountSection("投资账户", accounts.filter { [.investment, .fund, .stock].contains($0.type) }) } }.navigationTitle("资产").toolbar { Button("新增账户", systemImage: "plus") { adding = true } }.sheet(isPresented: $adding) { AccountEditorView() }.sheet(item: $editing) { AccountEditorView(account: $0) } } }
    private var assets: Decimal { accounts.filter { !$0.type.isLiability }.reduce(0) { $0 + $1.balance } }
    private var liabilities: Decimal { accounts.filter { $0.type.isLiability }.reduce(0) { $0 + abs($1.balance) } }
    private var netWorthCard: some View { VStack(alignment: .leading, spacing: 14) { HStack { Text("净资产").font(.subheadline).foregroundStyle(.secondary); Spacer(); Button(hideAmounts ? "显示金额" : "隐藏金额", systemImage: hideAmounts ? "eye.slash" : "eye") { hideAmounts.toggle() }.labelStyle(.iconOnly) }; Text(hideAmounts ? "••••••" : CurrencyFormatter.string(assets - liabilities)).font(.largeTitle.bold()).monospacedDigit(); HStack { Text("总资产 " + hidden(assets)); Spacer(); Text("总负债 " + hidden(liabilities)) }.font(.subheadline).foregroundStyle(.secondary) }.padding(20).background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 20)) }
    private func hidden(_ value: Decimal) -> String { hideAmounts ? "••••" : CurrencyFormatter.string(value) }
    @ViewBuilder private func accountSection(_ title: String, _ items: [Account]) -> some View { if !items.isEmpty { Section(title) { ForEach(items) { account in NavigationLink { AccountDetailView(account: account) } label: { AccountRow(account: account, hidden: hideAmounts) }.swipeActions { Button("编辑", systemImage: "pencil") { editing = account }.tint(.orange) } } } } }
}

struct AccountRow: View {
    let account: Account; let hidden: Bool
    var body: some View { HStack(spacing: 12) { Image(systemName: account.symbolName).foregroundStyle(Color(hex: account.colorHex)).frame(width: 40, height: 40).background(Color(hex: account.colorHex).opacity(0.14), in: Circle()); VStack(alignment: .leading) { Text(account.name).font(.headline); Text([account.institution, account.maskedNumber, account.type.title].filter { !$0.isEmpty }.joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) }; Spacer(); Text(hidden ? "••••" : CurrencyFormatter.string(account.balance, currency: account.currency)).monospacedDigit() }.accessibilityElement(children: .combine) }
}

struct AccountDetailView: View {
    @Query(sort: \FinanceTransaction.date, order: .reverse) private var transactions: [FinanceTransaction]
    let account: Account; @State private var editing = false
    private var history: [FinanceTransaction] { transactions.filter { $0.sourceAccount?.id == account.id || $0.destinationAccount?.id == account.id } }
    var body: some View { List { Section { VStack(spacing: 10) { Image(systemName: account.symbolName).font(.largeTitle).foregroundStyle(Color(hex: account.colorHex)); AmountText(amount: account.balance, currency: account.currency, font: .largeTitle.bold()); Text(account.type.title).foregroundStyle(.secondary) }.frame(maxWidth: .infinity).padding() }; Section("账户信息") { if !account.institution.isEmpty { LabeledContent("机构", value: account.institution) }; if !account.maskedNumber.isEmpty { LabeledContent("尾号", value: account.maskedNumber) }; if account.creditLimit > 0 { LabeledContent("信用额度", value: CurrencyFormatter.string(account.creditLimit)) }; if let day = account.billingDay { LabeledContent("账单日", value: "每月 \(day) 日") }; if let day = account.repaymentDay { LabeledContent("还款日", value: "每月 \(day) 日") } }; Section("本月") { LabeledContent("收入", value: CurrencyFormatter.string(FinanceCalculator.total(FinanceCalculator.transactions(history, in: .now), type: .income))); LabeledContent("支出", value: CurrencyFormatter.string(FinanceCalculator.total(FinanceCalculator.transactions(history, in: .now), type: .expense))) }; Section("账户流水") { if history.isEmpty { ContentUnavailableView("暂无流水", systemImage: "list.bullet") } else { ForEach(history) { NavigationLink { TransactionDetailView(transaction: $0) } label: { TransactionRow(transaction: $0) } } } } }.navigationTitle(account.name).toolbar { Button("编辑") { editing = true } }.sheet(isPresented: $editing) { AccountEditorView(account: account) } }
}

struct AccountEditorView: View {
    @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context
    var account: Account?
    @State private var name: String; @State private var type: AccountType; @State private var balance: String; @State private var currency: String; @State private var institution: String; @State private var number: String; @State private var limit: String; @State private var billingDay: Int; @State private var repaymentDay: Int; @State private var note: String; @State private var errorMessage: String?
    init(account: Account? = nil) { self.account = account; _name = State(initialValue: account?.name ?? ""); _type = State(initialValue: account?.type ?? .cash); _balance = State(initialValue: account.map { "\($0.balance)" } ?? "0"); _currency = State(initialValue: account?.currency ?? "CNY"); _institution = State(initialValue: account?.institution ?? ""); _number = State(initialValue: account?.maskedNumber ?? ""); _limit = State(initialValue: account.map { "\($0.creditLimit)" } ?? "0"); _billingDay = State(initialValue: account?.billingDay ?? 1); _repaymentDay = State(initialValue: account?.repaymentDay ?? 20); _note = State(initialValue: account?.note ?? "") }
    var body: some View { NavigationStack { Form { Section("基本信息") { TextField("账户名称", text: $name); Picker("账户类型", selection: $type) { ForEach(AccountType.allCases) { Text($0.title).tag($0) } }; TextField("余额", text: $balance).keyboardType(.decimalPad); Picker("币种", selection: $currency) { ForEach(["CNY", "USD", "EUR", "JPY"], id: \.self) { Text($0) } } }; Section("账户资料") { TextField("机构名称", text: $institution); TextField("尾号", text: $number); if type == .creditCard { TextField("信用额度", text: $limit).keyboardType(.decimalPad); Stepper("账单日：\(billingDay)", value: $billingDay, in: 1...28); Stepper("还款日：\(repaymentDay)", value: $repaymentDay, in: 1...28) }; TextField("备注", text: $note) } }.navigationTitle(account == nil ? "新增账户" : "编辑账户").toolbar { ToolbarItem(placement: .cancellationAction) { Button("取消") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("保存") { save() }.disabled(name.trimmingCharacters(in: .whitespaces).isEmpty) } }.alert("无法保存", isPresented: .constant(errorMessage != nil)) { Button("好") { errorMessage = nil } } message: { Text(errorMessage ?? "") } } }
    private func save() { guard let value = Decimal(string: balance), let credit = Decimal(string: limit) else { errorMessage = "金额格式无效"; return }; let model = account ?? Account(name: name); model.name = name; model.typeRaw = type.rawValue; model.balance = value; model.currency = currency; model.institution = institution; model.maskedNumber = number; model.creditLimit = credit; model.billingDay = type == .creditCard ? billingDay : nil; model.repaymentDay = type == .creditCard ? repaymentDay : nil; model.symbolName = type.symbol; model.note = note; if account == nil { context.insert(model) }; do { try context.save(); dismiss() } catch { errorMessage = error.localizedDescription } }
}
