import Foundation
import SwiftData

enum TransactionType: String, Codable, CaseIterable { case expense, income, transfer }
enum AccountType: String, Codable, CaseIterable { case cash, debit, credit, alipay, wechat, investment, fund, stock, providentFund, otherAsset, loan, otherLiability }
enum CategoryType: String, Codable { case expense, income }
enum BudgetPeriod: String, Codable { case month, year }

@Model final class Ledger { var id = UUID(); var name: String; var currency: String; var createdAt = Date(); @Relationship(deleteRule: .cascade, inverse: \Transaction.ledger) var transactions: [Transaction] = []; init(name: String = "默认账本", currency: String = "CNY") { self.name = name; self.currency = currency } }
@Model final class Category { var id = UUID(); var name: String; var symbolName: String; var colorHex: String; var typeRaw: String; var sortOrder: Int; var isEnabled = true; init(name: String, symbolName: String, colorHex: String, type: CategoryType, sortOrder: Int = 0) { self.name = name; self.symbolName = symbolName; self.colorHex = colorHex; self.typeRaw = type.rawValue; self.sortOrder = sortOrder }; var type: CategoryType { CategoryType(rawValue: typeRaw) ?? .expense } }
@Model final class Account { var id = UUID(); var name: String; var typeRaw: String; var balance: Decimal; var currency: String; var institution: String; var maskedNumber: String; var creditLimit: Decimal; var note: String; init(name: String, type: AccountType = .debit, balance: Decimal = 0, currency: String = "CNY", institution: String = "", maskedNumber: String = "", creditLimit: Decimal = 0, note: String = "") { self.name = name; self.typeRaw = type.rawValue; self.balance = balance; self.currency = currency; self.institution = institution; self.maskedNumber = maskedNumber; self.creditLimit = creditLimit; self.note = note }; var type: AccountType { AccountType(rawValue: typeRaw) ?? .debit } }
@Model final class Transaction { var id = UUID(); var typeRaw: String; var amount: Decimal; var date: Date; var note: String; var ledger: Ledger?; var category: Category?; var sourceAccount: Account?; var destinationAccount: Account?; var currency: String; var isReimbursable = false; var createdAt = Date(); var updatedAt = Date(); init(type: TransactionType, amount: Decimal, date: Date = .now, note: String = "", ledger: Ledger? = nil, category: Category? = nil, source: Account? = nil, destination: Account? = nil, currency: String = "CNY") { self.typeRaw = type.rawValue; self.amount = amount; self.date = date; self.note = note; self.ledger = ledger; self.category = category; self.sourceAccount = source; self.destinationAccount = destination; self.currency = currency }; var type: TransactionType { TransactionType(rawValue: typeRaw) ?? .expense } }
@Model final class Budget { var id = UUID(); var amount: Decimal; var periodRaw: String; var startDate: Date; var ledger: Ledger?; var category: Category?; init(amount: Decimal, period: BudgetPeriod = .month, startDate: Date = .now, ledger: Ledger? = nil, category: Category? = nil) { self.amount = amount; self.periodRaw = period.rawValue; self.startDate = startDate; self.ledger = ledger; self.category = category } }
@Model final class SavingsGoal { var id = UUID(); var name: String; var targetAmount: Decimal; var currentAmount: Decimal; var startDate: Date; var targetDate: Date?; init(name: String, targetAmount: Decimal, currentAmount: Decimal = 0, startDate: Date = .now, targetDate: Date? = nil) { self.name = name; self.targetAmount = targetAmount; self.currentAmount = currentAmount; self.startDate = startDate; self.targetDate = targetDate } }
@Model final class SavingsRecord { var id = UUID(); var amount: Decimal; var date: Date; var goal: SavingsGoal?; init(amount: Decimal, goal: SavingsGoal? = nil) { self.amount = amount; self.date = .now; self.goal = goal } }
@Model final class RecurringPayment { var id = UUID(); var name: String; var amount: Decimal; var nextPaymentDate: Date; var account: Account?; var category: Category?; var autoCreateTransaction: Bool; init(name: String, amount: Decimal, nextPaymentDate: Date = .now, autoCreateTransaction: Bool = false) { self.name = name; self.amount = amount; self.nextPaymentDate = nextPaymentDate; self.autoCreateTransaction = autoCreateTransaction } }
@Model final class InstallmentPlan { var id = UUID(); var name: String; var totalAmount: Decimal; var installmentCount: Int; var paidInstallments: Int; var installmentAmount: Decimal; var nextPaymentDate: Date; var account: Account?; init(name: String, totalAmount: Decimal, installmentCount: Int, installmentAmount: Decimal, nextPaymentDate: Date = .now) { self.name = name; self.totalAmount = totalAmount; self.installmentCount = installmentCount; self.paidInstallments = 0; self.installmentAmount = installmentAmount; self.nextPaymentDate = nextPaymentDate } }

enum SeedData { static let categories = [Category(name: "餐饮", symbolName: "fork.knife", colorHex: "#FF6B6B", type: .expense), Category(name: "购物", symbolName: "cart", colorHex: "#FF9F0A", type: .expense), Category(name: "住房", symbolName: "house", colorHex: "#0A84FF", type: .expense), Category(name: "交通", symbolName: "car", colorHex: "#30D158", type: .expense), Category(name: "娱乐", symbolName: "gamecontroller", colorHex: "#AF52DE", type: .expense), Category(name: "医疗", symbolName: "cross.case", colorHex: "#FF375F", type: .expense), Category(name: "工资", symbolName: "banknote", colorHex: "#30D158", type: .income), Category(name: "其他", symbolName: "ellipsis", colorHex: "#8E8E93", type: .expense)] }
